package com.gosun.healthwebsite.entity;
//Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
* BizAlarmCondition generated by hbm2java
*/
@Entity
@Table(name = "BIZ_ALARM_CONDITION", schema = "HEALTH")
public class BizAlarmCondition implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long conditionId;
	private Long equipmentTypeId;
	private String producer;
	private String moduleName;
	private String propertyName;
	private String expression;
	private String alarmResult;
	private String alarmLevel;
	private String alarmDesc;
	private Integer isCamera;
	private Long equipmentId;
	private String missionId;

	public BizAlarmCondition() {
	}

	public BizAlarmCondition(Long conditionId, Long equipmentTypeId, String producer, String moduleName,
			String propertyName, String expression, String alarmResult, String alarmLevel) {
		this.conditionId = conditionId;
		this.equipmentTypeId = equipmentTypeId;
		this.producer = producer;
		this.moduleName = moduleName;
		this.propertyName = propertyName;
		this.expression = expression;
		this.alarmResult = alarmResult;
		this.alarmLevel = alarmLevel;
	}
	

	public BizAlarmCondition(String propertyName, String expression,String alarmDesc, String missionId) {
		super();
		this.equipmentTypeId = (long)24;
		this.producer = "-1";
		this.moduleName = "-1";
		this.propertyName = propertyName;
		this.expression = expression;
		this.alarmResult = "摄像机视频异常";
		this.alarmLevel = "重要";
		this.alarmDesc = alarmDesc;
		this.isCamera = 1;
		this.equipmentId = null;
		this.missionId = missionId;
	}

	public BizAlarmCondition(Long conditionId, Long equipmentTypeId, String producer, String moduleName,
			String propertyName, String expression, String alarmResult, String alarmLevel, String alarmDesc) {
		this.conditionId = conditionId;
		this.equipmentTypeId = equipmentTypeId;
		this.producer = producer;
		this.moduleName = moduleName;
		this.propertyName = propertyName;
		this.expression = expression;
		this.alarmResult = alarmResult;
		this.alarmLevel = alarmLevel;
		this.alarmDesc = alarmDesc;
	}

	@Id
	@SequenceGenerator(name="SEQ_BIZ_ALARM_CONDITION", sequenceName="SEQ_BIZ_ALARM_CONDITION")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_BIZ_ALARM_CONDITION")
	@Column(name = "CONDITION_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(Long conditionId) {
		this.conditionId = conditionId;
	}

	@Column(name = "EQUIPMENT_TYPE_ID", nullable = false, precision = 10, scale = 0)
	public Long getEquipmentTypeId() {
		return this.equipmentTypeId;
	}

	public void setEquipmentTypeId(Long equipmentTypeId) {
		this.equipmentTypeId = equipmentTypeId;
	}

	@Column(name = "PRODUCER", nullable = false, length = 120)
	public String getProducer() {
		return this.producer;
	}

	public void setProducer(String producer) {
		this.producer = producer;
	}

	@Column(name = "MODULE_NAME", nullable = false, length = 120)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "PROPERTY_NAME", nullable = false, length = 120)
	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	@Column(name = "EXPRESSION", nullable = false, length = 200)
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "ALARM_RESULT", nullable = false, length = 120)
	public String getAlarmResult() {
		return this.alarmResult;
	}

	public void setAlarmResult(String alarmResult) {
		this.alarmResult = alarmResult;
	}

	@Column(name = "ALARM_LEVEL", nullable = false, length = 120)
	public String getAlarmLevel() {
		return this.alarmLevel;
	}

	public void setAlarmLevel(String alarmLevel) {
		this.alarmLevel = alarmLevel;
	}

	@Column(name = "ALARM_DESC", length = 120)
	public String getAlarmDesc() {
		return this.alarmDesc;
	}

	public void setAlarmDesc(String alarmDesc) {
		this.alarmDesc = alarmDesc;
	}
	
	@Column(name = "IS_CAMERA")
	public Integer getIsCamera() {
		return isCamera;
	}

	public void setIsCamera(Integer isCamera) {
		this.isCamera = isCamera;
	}
	
	@Column(name = "EQUIPMENT_ID")
	public Long getEquipmentId() {
		return equipmentId;
	}

	public void setEquipmentId(Long equipmentId) {
		this.equipmentId = equipmentId;
	}
	@Column(name = "MISSION_ID", length = 140)
	public String getMissionId() {
		return missionId;
	}

	public void setMissionId(String missionId) {
		this.missionId = missionId;
	}

}
