package com.gosun.healthwebsite.entity;
// Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * BizAlarmExtend generated by hbm2java
 */
@Entity
@Table(name = "BIZ_ALARM_EXTEND", schema = "HEALTH")
public class BizAlarmExtend implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long alarmExtendId;
	private Long alarmId;
//	private char focusFlag;
	private char processFlag;
	private String processResult;
	private Date processTime;
	private String processDesc;
	private String ids;
	private String processUser;


	@Id
	@SequenceGenerator(name="SEQ_BIZ_ALARM_EXTEND", sequenceName="SEQ_BIZ_ALARM_EXTEND")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_BIZ_ALARM_EXTEND")
	@Column(name = "ALARM_EXTEND_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getAlarmExtendId() {
		return this.alarmExtendId;
	}

	public void setAlarmExtendId(Long alarmExtendId) {
		this.alarmExtendId = alarmExtendId;
	}

	@Column(name = "ALARM_ID")
	public Long getAlarmId() {
		return this.alarmId;
	}

	public void setAlarmId(Long alarmId) {
		this.alarmId = alarmId;
	}

//	@Column(name = "FOCUS_FLAG", nullable = false, length = 1)
//	public char getFocusFlag() {
//		return this.focusFlag;
//	}
//
//	public void setFocusFlag(char focusFlag) {
//		this.focusFlag = focusFlag;
//	}

	@Column(name = "PROCESS_FLAG", nullable = false, length = 1)
	public char getProcessFlag() {
		return this.processFlag;
	}

	public void setProcessFlag(char processFlag) {
		this.processFlag = processFlag;
	}

	@Column(name = "PROCESS_RESULT", length = 120)
	public String getProcessResult() {
		return this.processResult;
	}

	public void setProcessResult(String processResult) {
		this.processResult = processResult;
	}

	@Column(name = "PROCESS_TIME", length = 7)
	public Date getProcessTime() {
		return this.processTime;
	}

	public void setProcessTime(Date processTime) {
		this.processTime = processTime;
	}

	@Column(name = "PROCESS_DESC", length = 120)
	public String getProcessDesc() {
		return this.processDesc;
	}

	public void setProcessDesc(String processDesc) {
		this.processDesc = processDesc;
	}
	
	@Transient
	public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}
	
	@Column(name = "PROCESS_USER")
	public String getProcessUser() {
		return processUser;
	}

	public void setProcessUser(String processUser) {
		this.processUser = processUser;
	}
	
	
	
	

}
