package com.gosun.healthwebsite.entity;
// Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizEquipmentStatus generated by hbm2java
 */
@Entity
@Table(name = "BIZ_EQUIPMENT_STATUS", schema = "HEALTH")
public class BizEquipmentStatus implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private BizEquipmentStatusId id;
	private String propertyValue;
	private Date updateTime;

	public BizEquipmentStatus() {
	}

	public BizEquipmentStatus(BizEquipmentStatusId id, String propertyValue, Date updateTime) {
		this.id = id;
		this.propertyValue = propertyValue;
		this.updateTime = updateTime;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "equipmentId", column = @Column(name = "EQUIPMENT_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "propertyName", column = @Column(name = "PROPERTY_NAME", nullable = false, length = 120)) })
	public BizEquipmentStatusId getId() {
		return this.id;
	}

	public void setId(BizEquipmentStatusId id) {
		this.id = id;
	}

	@Column(name = "PROPERTY_VALUE", nullable = false, length = 120)
	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	@Column(name = "UPDATE_TIME")
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
