package com.gosun.healthwebsite.entity;
// Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BizEquipmentStatusId generated by hbm2java
 */
@Embeddable
public class BizEquipmentStatusId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long equipmentId;
	private String propertyName;

	public BizEquipmentStatusId() {
	}

	public BizEquipmentStatusId(Long equipmentId, String propertyName) {
		this.equipmentId = equipmentId;
		this.propertyName = propertyName;
	}

	@Column(name = "EQUIPMENT_ID", nullable = false, precision = 10, scale = 0)
	public Long getEquipmentId() {
		return this.equipmentId;
	}

	public void setEquipmentId(Long equipmentId) {
		this.equipmentId = equipmentId;
	}

	@Column(name = "PROPERTY_NAME", nullable = false, length = 120)
	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BizEquipmentStatusId))
			return false;
		BizEquipmentStatusId castOther = (BizEquipmentStatusId) other;

		return (this.getEquipmentId() == castOther.getEquipmentId())
				&& ((this.getPropertyName() == castOther.getPropertyName())
						|| (this.getPropertyName() != null && castOther.getPropertyName() != null
								&& this.getPropertyName().equals(castOther.getPropertyName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEquipmentId().intValue();
		result = 37 * result + (getPropertyName() == null ? 0 : this.getPropertyName().hashCode());
		return result;
	}

}
