package com.gosun.healthwebsite.entity;
// Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * C3mFsu generated by hbm2java
 */
@Entity
@Table(name = "C3M_FSU", schema = "HEALTH")
public class C3mFsu implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String fsuId;
	private String fsuCode;
	private String name;
	private Long orgId;
	private String moduleType;

	public C3mFsu() {
	}

	public C3mFsu(String fsuId, String fsuCode, String name) {
		this.fsuId = fsuId;
		this.fsuCode = fsuCode;
		this.name = name;
	}

	public C3mFsu(String fsuId, String fsuCode, String name, Long orgId, String moduleType) {
		this.fsuId = fsuId;
		this.fsuCode = fsuCode;
		this.name = name;
		this.orgId = orgId;
		this.moduleType = moduleType;
	}

	@Id

	@Column(name = "FSU_ID", unique = true, nullable = false, length = 40)
	public String getFsuId() {
		return this.fsuId;
	}

	public void setFsuId(String fsuId) {
		this.fsuId = fsuId;
	}

	@Column(name = "FSU_CODE", nullable = false, length = 40)
	public String getFsuCode() {
		return this.fsuCode;
	}

	public void setFsuCode(String fsuCode) {
		this.fsuCode = fsuCode;
	}

	@Column(name = "NAME", nullable = false, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ORG_ID", precision = 10, scale = 0)
	public long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(long orgId) {
		this.orgId = orgId;
	}

	@Column(name = "MODULE_TYPE", length = 40)
	public String getModuleType() {
		return this.moduleType;
	}

	public void setModuleType(String moduleType) {
		this.moduleType = moduleType;
	}

}
