package com.gosun.healthwebsite.entity;
// Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysEquipmentType generated by hbm2java
 */
@Entity
@Table(name = "SYS_EQUIPMENT_TYPE", schema = "HEALTH")
public class SysEquipmentType implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long equipmentTypeId;
	private String name;
	private String remark;

	public SysEquipmentType() {
	}

	public SysEquipmentType(Long equipmentTypeId, String name) {
		this.equipmentTypeId = equipmentTypeId;
		this.name = name;
	}
	
	public SysEquipmentType(Long equipmentTypeId, String name, String remark) {
		this.equipmentTypeId = equipmentTypeId;
		this.name = name;
		this.remark = remark;
	}

	@Id

	@Column(name = "EQUIPMENT_TYPE_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getEquipmentTypeId() {
		return this.equipmentTypeId;
	}

	public void setEquipmentTypeId(Long equipmentTypeId) {
		this.equipmentTypeId = equipmentTypeId;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "REMARK", length = 120)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
