package com.gosun.healthwebsite.entity;
// Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.gosun.core.utils.date.DateTimeUtils;

/**
 * BizMask generated by hbm2java
 */
@Entity
@Table(name = "VIEW_UI_EQ_NET_STATUS", schema = "HEALTH")
public class UIEquipmentNetworkStatus implements java.io.Serializable {
	
	/**
	 * @Fields serialVersionUID : TODO
	 */
	private static final long serialVersionUID = 9089038767652140449L;
	/**
	 * @Fields serialVersionUID : TODO
	 */
	private Long equipmentId;
	private String pathName;
	private String path;
	private String equipmentName;
	private String  equipmentTypeName;
	private String producer;
	private String moduleName;
	private String netAddress;
	private String netStatus;
//	private String alarmCount;
//	private String lastProcessTime;
	private Date lastUpdateDate;
	private String lastUpdateTime;
//	private String processResult;
//	private String processDesc;
	private String focusFlag;
	private String orgId;
	private String repairFlag;
	private String isMask;
	private Integer alarmCount;

	
	
	
	
	
	@Id
	@Column(name = "EQUIPMENT_ID")
	public Long getEquipmentId() {
		return equipmentId;
	}

	public void setEquipmentId(Long equipmentId) {
		this.equipmentId = equipmentId;
	}
	
	@Column(name = "PATH_NAME")
	public String getPathName() {
		return pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}
	
	@Column(name = "EQUIPMENT_NAME")
	public String getEquipmentName() {
		return equipmentName;
	}

	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName;
	}
	
	@Column(name = "EQUIPMENT_TYPE_NAME")
	public String getEquipmentTypeName() {
		return equipmentTypeName;
	}

	public void setEquipmentTypeName(String equipmentTypeName) {
		this.equipmentTypeName = equipmentTypeName;
	}
	
	@Column(name = "PRODUCER")
	public String getProducer() {
		return producer;
	}

	public void setProducer(String producer) {
		this.producer = producer;
	}
	
	@Column(name = "MODULE_NAME")
	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}
	
	@Column(name = "NET_ADDRESS")
	public String getNetAddress() {
		return netAddress;
	}

	public void setNetAddress(String netAddress) {
		this.netAddress = netAddress;
	}
	
	@Column(name = "NET_STATUS")
	public String getNetStatus() {
		return netStatus;
	}

	public void setNetStatus(String netStatus) {
		this.netStatus = netStatus;
	}

	
//	@Column(name = "ALARM_COUNT")
//	public String getAlarmCount() {
//		return alarmCount;
//	}
//
//	public void setAlarmCount(String alarmCount) {
//		this.alarmCount = alarmCount;
//	}
	
//	@Column(name = "LAST_PROCESS_TIME")
//	public String getLastProcessTime() {
//		return lastProcessTime;
//	}
//
//	public void setLastProcessTime(String lastProcessTime) {
//		this.lastProcessTime = lastProcessTime;
//	}
	
	@Transient
	public String getLastUpdateTime() {
		if(this.lastUpdateDate!=null){
			return DateTimeUtils.convertDateToStringByFormat(this.lastUpdateDate);
		}
		return "";
	}
	
	@Column(name = "LAST_UPDATE_TIME")
	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	//	@Column(name = "PROCESS_RESULT")
//	public String getProcessResult() {
//		return processResult;
//	}
//
//	public void setProcessResult(String processResult) {
//		this.processResult = processResult;
//	}
//
//	@Column(name = "PROCESS_DESC")
//	public String getProcessDesc() {
//		return processDesc;
//	}
//
//	public void setProcessDesc(String processDesc) {
//		this.processDesc = processDesc;
//	}
//
	@Column(name = "PATH")
	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}
	
	@Column(name = "FOCUS_FLAG")
	public String getFocusFlag() {
		return focusFlag;
	}

	public void setFocusFlag(String focusFlag) {
		this.focusFlag = focusFlag;
	}


	
	@Column(name = "ORG_ID")
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "REPAIR_FLAG")
	public String getRepairFlag() {
		return repairFlag;
	}

	public void setRepairFlag(String repairFlag) {
		this.repairFlag = repairFlag;
	}

	@Column(name = "IS_MASK")
	public String getIsMask() {
		return isMask;
	}

	public void setIsMask(String isMask) {
		this.isMask = isMask;
	}

	@Column(name = "ALARM_COUNT")
	public Integer getAlarmCount() {
		return alarmCount;
	}

	public void setAlarmCount(Integer alarmCount) {
		this.alarmCount = alarmCount;
	}
}
