package com.gosun.healthwebsite.entity;
// Generated 2016-5-18 9:19:52 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BizMask generated by hbm2java
 */
@Entity
@Table(name = "VIEW_UI_SYSDEV_STATUS", schema = "HEALTH")
public class UISysDevStatus implements java.io.Serializable {
	

	/**
	 * @Fields serialVersionUID : TODO
	 */
	private static final long serialVersionUID = 8468519409435548046L;
	/**
	 * @Fields serialVersionUID : TODO
	 */
	private Long dataId;
	private Long equipmentId;
	private String propertyName;
	private String propertyValue;
	private String alarmEventViewID;
	private String alarmType;
	private String orgId;
	
	
	@Id
	@Column(name = "DATA_ID")
	public Long getDataId() {
		return dataId;
	}

	public void setDataId(Long dataId) {
		this.dataId = dataId;
	}
	
	
	@Column(name = "EQUIPMENT_ID")
	public Long getEquipmentId() {
		return equipmentId;
	}


	public void setEquipmentId(Long equipmentId) {
		this.equipmentId = equipmentId;
	}
	

	
	@Column(name = "PROPERTY_NAME")
	public String getPropertyName() {
		return propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}
	
	@Column(name = "PROPERTY_VALUE")
	public String getPropertyValue() {
		return propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}
	
	@Column(name = "ALARMEVENT_VIEW_ID")
	public String getAlarmEventViewID() {
		return alarmEventViewID;
	}

	public void setAlarmEventViewID(String alarmEventViewID) {
		this.alarmEventViewID = alarmEventViewID;
	}

	@Column(name="ALARM_TYPE")
	public String getAlarmType() {
		return alarmType;
	}

	public void setAlarmType(String alarmType) {
		this.alarmType = alarmType;
	}
	
	@Column(name="ORG_ID")
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}
}
